version: "2"
formatters:
  enable:
    - gofmt
    - goimports
    - golines
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - iface
    - inamedparam
    - ineffassign
    - interfacebloat
    - iotamixing
    - loggercheck
    - misspell
    - modernize
    - nestif
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    # - wrapcheck
